### ISSUE TITLE
How install packages in boot2docker

### ISSUE THREAD

**Issue by pyotr777** [boot2docker/boot2docker#1070]
I need to install bash, shadow-untils and some other packages in boot2docker.
I could install bash with
```
tce-load -wi bash
```

But when I try the same command with shadow-utils :
```
docker@default:~/dockerIaaSTools$ tce-load -wi shadow-utils
Downloading: shadow-utils.tcz
Connecting to distro.ibiblio.org (152.19.134.43:80)
wget: server returned error: HTTP/1.1 404 Not Found
md5sum: shadow-utils.tcz.md5.txt: No such file or directory
Error on shadow-utils.tcz
```

I also tried to download it from http://ftp.nluug.nl/os/Linux/distr/tinycorelinux/tcz/ and install with -i :
```
docker@default:~$ tce-load -i shadow-utils
mount: mounting /dev/loop6 on /tmp/tcloop/shadow-utils failed: Invalid argument
```

I need shadow-utils because I need commands `useradd`, `userdel`, `usermod`,  `groupadd`, `groupdel`, and `groupmod`.

My specs:
Boot2Docker version 1.8.2, build master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
Docker version 1.8.2, build 0a8c2e3

**Comment by rohanjoseph** [comment]
docker-machine create -d virtualbox --virtualbox-import-boot2docker-vm boot2docker-vm docker-vm
 i am trying to hit this command and my boot2docker of version 1.8.2 is not allowing cause i have a limited privilleges as i am signed up with user as docker. can anyone help me

**Comment by boxofrox** [comment]
@pyotr777 the packages on nluug.nl were created in 2009.  The issue was mentioned on the TCL forums, but never addressed [1].

Boot2docker does have `adduser`, `addgroup`, `deluser`, `delgroup` commands.  While not identical to the shadow-util variety, those will help you get started.  Unfortunately, I didn't find an alternative to `usermod` or `groupmod`.

[1] http://forum.tinycorelinux.net/index.php?topic=13099.0

**Comment by boxofrox** [comment]
@pyotr777 

Also, keep in mind that TinyCoreLinux (TCL) is intended to be a readonly distro, and provides options for persisting configuration files.  Which is to say, even if you installed shadow-utils, your changes would be lost on the next reboot.  Chapter 1.10 and 24.1 of the Core Book [1] discusses how to backup and restore files and add a new user.

[1] http://tinycorelinux.net/book.html

Out of the box boot2docker disables the restore system.  We can write Dockerfiles that build custom boot2docker isos.  If you're interested in trying it out, let me know.

**Comment by pyotr777** [comment]
@boxofrox 
Thank you for the detailed answer! 
Custom boot2docker won't work for me, cause I'm thinking of a tool that anyone could use, not only myself.

**Comment by boxofrox** [comment]
You're welcome.  There might still be hope.  Boot2docker may switch to Debian instead of TCL in the future.  See #1065 and https://github.com/docker/boot2docker .

**Comment by pyotr777** [comment]
Great news! Thank you!

**Comment by ovidiubuligan** [comment]
I also want to intall `du` utility  but tcz packages are confusing , I don't know if `du` even exists.
The reason behind it is because I want to find out disk usage of acontainer:
with ```du -d 2 -h /var/lib/docker/devicemapper | grep `docker inspect -f "{{.Id}}" <container_name>````
See second answear from: http://stackoverflow.com/questions/26753087/docker-how-to-analyze-a-containers-disk-usage.
Does `du` utility exist for tinycore ?
