### ISSUE TITLE
`--userns-remap` feature not supported?

### ISSUE THREAD

**Issue by mrmachine** [boot2docker/boot2docker#1134]
When I add `--userns-remap=defaut` to `EXTRA_ARGS` in `/var/lib/boot2docker/profile`, then `docker-machine start ...` reports:

`Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded`

When I stop docker with `sudo /etc/init.d/docker stop` and then run the command manually, I get a fatal error:

```
docker@default:~$ sudo /usr/local/bin/docker daemon -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=vmwarefusion --tlsverify --tlscacer
t=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs --userns-remap=default
UEBU[0000] Trusting certs with subjects: [010
tailee] 
DEBU[0000] docker group found. gid: 100                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Server created for HTTP on tcp (0.0.0.0:2376) 
FATA[0000] Error starting daemon: Error during "dockremap" user creation: Error adding group "dockremap": Cannot add group; no groupadd/addgroup binary found 
```

But there is an `addgroup` binary:

```
docker@default:~$ which addgroup
/usr/sbin/addgroup
```

If I add my own group and user manually, and try to use those, I get a different error:

```
docker@default:~$ sudo addgroup -g 20 osx_staff
docker@default:~$ sudo adduser -G osx_staff -SDHu 501 osx_tailee
docker@default:~$ sudo /usr/local/bin/docker daemon -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=vmwarefusion --tlsverify --tlscacer
t=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs --userns-remap=501:20
UEBU[0000] Trusting certs with subjects: [010
tailee] 
DEBU[0000] docker group found. gid: 100                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Server created for HTTP on tcp (0.0.0.0:2376) 
INFO[0000] User namespaces: ID ranges will be mapped to subuid/subgid ranges of: osx_tailee:osx_staff 
FATA[0000] Error starting daemon: Can't create ID mappings: open /etc/subuid: no such file or directory 
```

I am not a linux guru. I tried reading the docker docs and linux man page for `subuid`, and came away less than enlightened.

What do I need to do to start using the new user namespace feature of docker 1.10 on OS X with `docker-machine` and `boot2docker`? I just want files written to volumes I share from my mac into a container to have the same owner and group as on my OS X machine (uid 501, gid 20).

**Comment by disenchant** [comment]
I'm having the exact same problem on boot2docker v1.10.1 and at least on the Docker IRC nobody seemed to have a solution yet.

ping @diogomonica: I think this is a pretty important issue if we would like more users to try out the new user namespaces feature in Docker. So maybe you know the right person to have a look at this :innocent:

**Comment by diogomonica** [comment]
@tianon any insights into what might be happening here?

**Comment by tianon** [comment]
Looks like the problem with `addgroup` is: https://github.com/docker/docker/blob/ad861876e8bb86091527f31fc944205743e5ce85/pkg/idtools/usergroupadd_linux.go#L29

It uses `addgroup --gid`, which doesn't work on busybox's `addgroup`:
```console
docker@boot2docker:~$ addgroup --help
BusyBox v1.23.1 (2015-02-22 15:53:49 UTC) multi-call binary.

Usage: addgroup [-g GID] [-S] [USER] GROUP

Add a group or add a user to a group

	-g GID	Group id
	-S	Create a system group

```

After I do `addgroup dockremap` manually and run again, I get the same error, so there's probably a bug somewhere there too, but I'm guessing we're going to run into trouble with that `adduser` line too, given busybox's `adduser`:
```console
docker@boot2docker:~$ adduser --help
BusyBox v1.23.1 (2015-02-22 15:53:49 UTC) multi-call binary.

Usage: adduser [OPTIONS] USER [GROUP]

Create new user, or add USER to GROUP

	-h DIR		Home directory
	-g GECOS	GECOS field
	-s SHELL	Login shell
	-G GRP		Add user to existing group
	-S		Create a system user
	-D		Don't assign a password
	-H		Don't create home directory
	-u UID		User id

```

I can confirm that after additionally doing `adduser -G dockremap dockremap` (had to `-G` because the `dockremap` group already existed from previously and I get `adduser: group 'dockremap' in use` otherwise), I get:
```
time="2016-02-22T23:10:27.657878899Z" level=info msg="User namespaces: ID ranges will be mapped to subuid/subgid ranges of: dockremap:dockremap" 
time="2016-02-22T23:10:27.657916404Z" level=fatal msg="Error starting daemon: Can't create ID mappings: open /etc/subuid: no such file or directory" 
```

cc @estesp, since we're over my head now -- why would Docker be failing if `/etc/subuid` doesn't exist at all?  What's responsible for creating that file on other distributions?

If I touch both `/etc/subuid` and `/etc/subgid`, I get `time="2016-02-22T23:12:51.966438848Z" level=fatal msg="Error starting daemon: Can't create ID mappings: No subuid ranges found for user \"dockremap\"" ` -- are users responsible for creating this file themselves?  Do we have documentation for this already somewhere?  (The only docs reference I can find is one that points to some external blog post in https://docs.docker.com/engine/security/security/ -> http://s3hh.wordpress.com/2013/07/19/creating-and-using-containers-without-privilege/, but that article also states that "Today, Docker does not directly support user namespaces, but ...")

**Comment by estesp** [comment]
For distros and/or environments that don't support the full tools I assume we will need to add some manual instructions on setup.  Also, if there is a way to make the use of `adduser` and `addgroup` more accomodating/graceful in failure, that is probably good as well.

The shadow-utils pkg is supposed to carry support for creating ranges in `/etc/sub{u,g}id` if I remember correctly, and distros are in various states of supporting that properly.  Ubuntu works out of the box; for some reason on recent Fedora you have to `touch` the files first, and then it all magically works...so :)

Happy to help make this all more robust when we aren't on a full distro/using busybox, although some of that may only be "here's the manual path" docs

**Comment by tianon** [comment]
Ok, that's fair -- is there some specific spot in the code you can point me to for sane values/users I could hard-code in the ISO so that at least using `default` works out of the box?

**Comment by tianon** [comment]
More specifically, if I pre-create the `dockremap` user/group, what would make sense to put into `/etc/subuid` and `/etc/subgid`?

**Comment by estesp** [comment]
Probably the most seminal discussion on this is the LXC 1.0 release blog that discusses the settings in `/etc/sub{u,g}id`: https://www.stgraber.org/2014/01/17/lxc-1-0-unprivileged-containers/

That has the most commonly seen default for the first user to be assigned a range in `/etc/sub*id` files:
```
username:100000:65536
```

In your case, I assume you can pre-create the user and group `dockremap`, and then pre-create the `/etc/subuid` and `/etc/subgid` files with exactly the same contents as above, with **username** replaced with `dockremap`.

Specific details on those files are here: http://man7.org/linux/man-pages/man5/subuid.5.html
and http://man7.org/linux/man-pages/man5/subgid.5.html

**Comment by SvenDowideit** [comment]
confirmed :)

```
$ uname -a
Linux default 4.1.17-boot2docker #1 SMP Mon Feb 1 16:37:01 UTC 2016 x86_64 GNU/Linux
$ ps aux | grep nginx
100000    7680  0.7  0.0  31596  4940 ?        Ss   05:36   0:00 nginx: master process nginx -g daemon off;
100104    7686  0.0  0.0  31972  2888 ?        S    05:36   0:00 nginx: worker process
docker    7691  0.0  0.0   9768   908 pts/0    S+   05:36   0:00 grep nginx
```

**Comment by crdil** [comment]
My containers won't show up after I have started docker with the following command:
`/usr/bin/docker daemon -H fd:// -g /home/docker --userns-remap=default`

I tried to set the /home/docker directory to user and group dockremap, but it didn't help. Is it suppose to work this way so I have to create new containers, that only dockremap user/group has access to?

**Comment by SvenDowideit** [comment]
yes, when you're using userns-remap, there is a new sub dir that is used for the images `/usr/lib/docker/10000000:100000` or something - when images are pulled / created using `userns-remap`, they are written with the remapped ownerships to avoid slowing file access down in use.

**Comment by dhawal55** [comment]
Ok, i ended up creating `/etc/subuid` and `/etc/subguid` with following text `dockuser:100000:65536`. Started docker daemon as `docker daemon --userns-remap:dockuser`. Now i get error when starting any container:

```
docker run nordstrom/helloworld
Timestamp: 2016-06-16 17:05:00.309899208 +0000 UTC
Code: System error

Message: operation not permitted

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@240
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@111
---
7: goexit
Package: runtime
File: asm_amd64.s@1721
docker: Error response from daemon: Cannot start container 0531588983fdeb0bf074f0c0cd0092632bcead707cbc1721d76cb767a6adbd21: [9] System error: operation not permitted.
```

**Comment by QianJin2013** [comment]
Hello, it seems `--userns-remap` **OK** now (boot2docker 1.11.2 in docker-machine version 0.7.0, build a650a40, Mac OS X),
but boot2docker lose my customized setting files after restart, that is another problem.

This is how i do the --userns-remap, most are same as what the issue poster did.
Differences are:
`--userns-remap=default` -> `--userns-remap=osx_tailee:osx_staff`
and add `/etc/subuid`  `/etc/subgid`  (See <a href="https://blog.yadutaf.fr/2016/04/14/docker-for-your-users-introducing-user-namespace/">this</a> )

```
$ docker-machine ssh rethink   # rethink is my vm name, please change it to yours.
...
docker@rethink:~$ sudo vi /var/lib/boot2docker/profile 
...
EXTRA_ARGS='
--label provider=virtualbox
--userns-remap=osx_tailee:osx_staff            #####this is what i add#####
'
...
```

then restart, cause same error `Maximum number of retries (10) exceeded`, docker daemon is not started,

then,
```
docker@rethink:~$ sudo addgroup -g 20 osx_staff
docker@rethink:~$ sudo adduser -G osx_staff -SDHu 501 osx_tailee

```

then prepare uid/gid range for container
```
docker@rethink:~$ sudo vi /etc/subuid
osx_tailee:100000:65536

docker@rethink:~$ sudo vi /etc/subgid
osx_staff:200000:65536
```

then start docker daemon
```
docker@rethink:~$ sudo /usr/local/bin/docker daemon -D -g "/var/lib/docker" -H unix:// -H tcp://0.0.0.0:2376 --label provider=virtualbox \
--userns-remap=osx_tailee:osx_staff --tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs

...
DEBU[0000] docker group found. gid: 100                 
...
INFO[0000] API listen on [::]:2376                      
INFO[0000] API listen on /var/run/docker.sock           
```

Then i run docker container. There are strange thing here: previously used docker image will be treated as "not exist", get downloaded again.
```
$ docker run -it -v /bin:/xxx busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
8ddc19f16526: Pull complete 
Digest: sha256:a59906e33509d14c036c8678d687bd4eec81ed7c4b8ce907b888c607f6a1e0e6
Status: Downloaded newer image for busybox:latest
/ # id
uid=0(root) gid=0(root) groups=10(wheel)
/ # ls /xxx
VBoxClient     cat            dd             echo           gunzip         ln             mount          printenv       ...
...
/ # echo hi > /xxx/a
sh: can't create /xxx/a: Permission denied
```

So far it works as expected. 
But when i restart boot2docker, it lost the two users created by me, and /etc/subuid, /etc/subgid, 

I think the reason is because this VM is configured to start from `boot2docker.iso` which does not save my modification.
