### ISSUE TITLE
Empty sshd_config file on boot => SFTP failure

### ISSUE THREAD

**Issue by brettdh** [boot2docker/boot2docker#1172]
```
$ docker-machine create --driver vmwarefusion --vmwarefusion-memory-size 4096 --vmwarefusion-cpu-count 4  sftp-test
<snip>
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env sftp-test
```

First sign that something was wrong:

```
$ sftp -i ~/.docker/machine/machines/sftp-test/id_rsa docker@192.168.176.203 
subsystem request failed on channel 0
Connection closed
```

In `/var/log/boot2docker.log`:

```
mv: can't rename '/usr/local/etc/ssh/ssh_config_example': No such file or directory
mv: can't rename '/usr/local/etc/ssh/sshd_config_example': No such file or directory
grep: /usr/local/etc/ssh/sshd_config: No such file or directory
```

Contents of `/usr/local/etc/ssh/sshd_config` on boot:

```
$ docker-machine ssh sftp-test "cat /usr/local/etc/ssh/sshd_config"
UseDNS no
```

According to the contents of [openssh-server](https://packages.debian.org/jessie/amd64/openssh-server/filelist), it seems like [/etc/rc.d/sshd](https://github.com/boot2docker/boot2docker/blob/858cccc2059e382f2c4f037385d1049df5ac4239/rootfs/rootfs/etc/rc.d/sshd#L16) should be copying `sshd_config` from `/usr/share/doc/openssh-client/examples/sshd_config` instead - but I'm just guessing.

Oddly, the pristine file is present at `/usr/local/etc/ssh/sshd_config.orig`.

**Comment by simonvanderveldt** [comment]
@brettdh @tianon it seems like this was introduced by the switch to TCL7 in #1147
TCL6's openssh contained the relevant files `/usr/local/etc/ssh/ssh_config_example` and `/usr/local/etc/ssh/sshd_config_example`, see http://distro.ibiblio.org/tinycorelinux/6.x/x86_64/tcz/openssh.tcz.list
For TCL7 these files have been renamed, see http://distro.ibiblio.org/tinycorelinux/7.x/x86_64/tcz/openssh.tcz.md5.txt where they're now called `/usr/local/etc/ssh/ssh_config.orig` and `/usr/local/etc/ssh/sshd_config.orig`
I've compared the old and new ones and they are indeed the same files (with some slight changes) that now have a different name.

For people with an existing boot2docker install there's no impact because the initial copying has been done with the old/then correct filenames and this part doesn't get triggered for them again.
For new/clean installs it will fail though. I'll create a PR to fix it.
