### ISSUE TITLE
when is excon updated to make docker-api work again?

### ISSUE THREAD

**Issue by philkunz** [boot2docker/boot2docker#1181]
see here: https://github.com/swipely/docker-api/issues/415

**Comment by thaJeztah** [comment]
What needs to be updated in boot2docker? The linked issue talks about 1.10.3 binaries that are built with an incorrect version of Go (the official 1.10.3 binaries in the docker repository are developed for, and tested against a different Go version, because there were some known issues with Go 1.6 and the docker 1.10.3 codebase); Docker 1.12 has a patch to allow building it on Go 1.6, while keeping compatibility with older clients (see https://github.com/docker/docker/pull/22000)

**Comment by philkunz** [comment]
I confused something, sorry!
