### ISSUE TITLE
How to Scan boot2docker VM for Malware's/ Virus ??

### ISSUE THREAD

**Issue by anandnevase** [boot2docker/boot2docker#1187]
How to can boot2docker VM for Malware's/ Virus . ?? 

I am trying to install clamav antivirus but clamav installation is failing.

**Comment by educatedwarrior** [comment]
Good question.   My version of boot2docker came installed with some Trojan Horse pulling crap down from sektori.org.    It was automatically creating and destroying containers and wreaking havoc on my wan and lan.

**Comment by tianon** [comment]
If you must scan the ISO for viruses, you should be able to use your host's virus scanner to do so -- simply point it at the ISO.  If it isn't able to look inside and scan the contents of the ISO appropriately, you should probably get a new virus scanner.

Closing, since there's nothing we can fix in the ISO here (we definitely don't include anything that calls out to sektori.org).
