### ISSUE TITLE
docker-machine freezes

### ISSUE THREAD

**Issue by mjrgr** [boot2docker/boot2docker#1222]
Hi,

I have a problem when I try to start a new VM using docker-machine:

```
docker-machine --debug create -d xenserver --xenserver-server ***** --xenserver-username root --xenserver-password ******* --xenserver-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v1.12.3/boot2docker.iso --xenserver-memory-size 2048 test-vm
```

docker-machine freezes at this line
`(test-vm) Waiting for VM to start...`

But it works when I use 1.12.0 version of **boot2docker** iso file

**Comment by tianon** [comment]
Sorry for the long delay -- I can only imagine there's something going wrong with your Xen Server instance (or with boot2docker's admittedly experimental/poorly-maintained support for running as a Xen guest).

Since there's not much we can do about this without further debugging into the root cause (and how to fix it), I'm going to close. :+1:
