### ISSUE TITLE
Unabled to RUN apt-get update / install 

### ISSUE THREAD

**Issue by JoThomsen** [boot2docker/boot2docker#1223]
Hello,

I'm unabled to build Docker Images with apt-get in the RUN parts.
There was no error when downloaded the baseimage. 
I tried it on different computer with the latest version of the docker Toolbox.
Windows 7 / 10 

And i have no internet problemes or firewall-rules.

Error:
E: Unable to locate package vim-tiny
E: Unable to locate package wget
E: Unable to locate package unzip
E: Unable to locate package leafpad
E: Unable to locate package language-pack-de-base
The command '/bin/sh -c apt-get install -y      vim-tiny
& rm -rf /tmp/*' returned a non-zero code: 100

I think there is some problem with some of the latest releases, the machine worked 3-4 weeks very fine.

Thanks for help!

**Comment by AkihiroSuda** [comment]
The issue report is not sufficient to analyze..

 * What's your hypervisor and virtual NIC?
 * Is your virtual NIC detected on your B2D? (you may want to use `ip`)
 * Did your B2D obtain IP address successfully from DHCP? (ditto)
 * Can you ping (e.g.) 8.8.8.8?
 * Is your DNS working?

Probably this kind of question should be discussed in stack overflow

**Comment by JoThomsen** [comment]
I used VirtualBox(Version 5.1.8) and the latest B2D (1.12.3 version and tried it with 1.12.2) 
The Kernel Version is 4.4.24-boot2docker.
I can ping this IP. 
I also can download Baseimages and run them.
My DNS is working i tried it with some different adresses...
I will ask the question at stack overflow too.

**Comment by Rots** [comment]
`apt-get update` missing?

**Comment by JoThomsen** [comment]
For e.g.
FROM ubuntu:14.04

RUN apt-get clean
RUN apt-get update -y
RUN apt-get install -y mercurial
RUN apt-get install -y git
RUN apt-get install -y python

The Error will happen at the apt-get update

**Comment by yosifkit** [comment]
The only time I have seen the `E: Unable to locate package wget` is when there is no apt cache and usually points to a missing or failed `apt-get update`. It could also be related to the apt cache being from a different layer in the image (and so it becomes outdated) and will not be updated on a `docker build` when a new package is added to the list.  I would minimally recommend doing a `--no-cache` docker build or pulling the latest `ubuntu:14.04` image. 

I would also recommend writing your apt installs on one line so that the created images end up slimmer:
```Dockerfile
FROM ubuntu:14.04
RUN apt-get update \
  && apt-get install -y wget mercurial git python \
  && rm -rf /var/lib/apt/lists/*
```

**Comment by tianon** [comment]
Issue appears both stale and environmental (not something wrong with the ISO), so I'm going to close. :+1:
