### ISSUE TITLE
EFI/UEFI booting

### ISSUE THREAD

**Issue by Manouchehri** [boot2docker/boot2docker#1239]
We should add support for booting the native Linux kernel EFI stub. 

Tiny Core Linux added UEFI support back in 2015, so it shouldn't be too difficult. http://linux.softpedia.com/blog/Tiny-Core-Linux-6-2-Brings-NFS4-Support-and-a-Legacy-BIOS-UEFI-Multi-boot-Version-480149.shtml

**Comment by yosifkit** [comment]
I am a bit hesitant, especially since the documentation from [virtualbox](https://www.virtualbox.org/manual/ch03.html#efi) makes it sound like it is still experimental, even though the current release is `5.1.14`.
> Starting with release 3.1, VirtualBox includes experimental support for the Extensible Firmware Interface (EFI), which is a new industry standard intended to eventually replace the legacy BIOS as the primary interface for bootstrapping computers and certain system services later.

There are quite a few EFI fixes listed in their [changelogs](https://www.virtualbox.org/wiki/Changelog), so maybe I am wrong about it still being "experimental".  Here is a sampling of fixes across versions 4.0 to 5.1:
> - EFI: fixed access to devices attached to SATA port 2 and higher (bug 15607)
> - VMM: fixed a potential hang with 32-bit EFI guests on Intel CPUs (VT-x without unrestricted guest execution)
> - SATA: fixed hotplug flag handling when EFI is used
> - EFI: improved performance of IDE disk access
> - EFI: properly announce the amount of RAM for big VMs (bugs 11103 and 13211)
> - EFI: don't fail with 64-bit guests on 32-bit hosts (bug 11456)
> - EFI: support for SATA disks and CDROMs

cc @tianon and @nathanleclaire, what do you think about adding EFI support to boot2docker and maybe even turning it on by default in virtualbox via docker-machine?

**Comment by Manouchehri** [comment]
EFI booting doesn't have to be the default, but it would be nice to have as an option.

**Comment by nathanleclaire** [comment]
Yeah, definitely not default, but I'd be happy to merge support for such a feature into Machine if offered

**Comment by tianon** [comment]
My only concern would be the added maintainence burden -- I think the idea
is interesting, but I'd want to be sure that the amount of added bits that
need to be maintained in b2d are kept very minimal (especially since it
won't get much testing after it's in, during and between releases, for
example).

**Comment by tianon** [comment]
Closing given that EFI/UEFI support is not something we're going to pursue for the maintenance/testing reasons noted above.  Sorry!
