### ISSUE TITLE
OSX: Transition from sleep to hibernate causes sleep wake failure and restart

### ISSUE THREAD

**Issue by jscheel** [boot2docker/boot2docker#1246]
Currently using vmware fusion 8 on osx 10.11.6. Without fail, if I leave docker running when my macbook pro goes to sleep, my computer will restart itself when it transitions from sleep to hibernate (3 hours, as specified by the `standbydelay` listed in `pmset -g`. I thought it might be part of this same issue here https://github.com/docker/for-mac/issues/85, but running inside boot2docker.

**Comment by tianon** [comment]
Sorry for the long delay!  I have no idea on this one -- I _imagine_ it's probably related to something VMware is doing, but I'm stabbing in the dark.  If you're still having this problem, I'd recommend reaching out to a VMware Fusion specific support group / forum (since I don't think there's anything we can do either to cause this or to fix this within the boot2docker distribution itself). :heart:
