### ISSUE TITLE
Need TLS certs for XXX

### ISSUE THREAD

**Issue by ifeengwd2012** [boot2docker/boot2docker#1272]
software version:
```
docker for window: v17.06.2-ce
docker-machine:v0.12.2
boot2docker:v17.06.2-ce
vitualbox:v5.1.26
```

error information:
```
docker@test1:~$ sudo /etc/init.d/docker status
Docker daemon is not running
docker@test1:~$ sudo /etc/init.d/docker start
Need TLS certs for test1,127.0.0.1,10.0.2.15,192.168.99.100   //error
```

error trace:
```
1、docker-machine create -d virtualbox test1
2、docker-machine env test1
3、eval xxx (export xxx)
4、docker-machine ssh test1
5、vim /var/lib/boot2docker/profile
6、sudo /etc/init.d/docker restart        //error
7、exit ;
8、docker-machine restart test1         //error
```

**Comment by ifeengwd2012** [comment]
临时的解决办法，去掉tls，具体做法：
`
1、docker-machine start test1
2、docker-machine ssh test1
3、sudo cp /var/lib/boot2docekr/profile /var/lib/boot2docker/profile-bak
4、sudo vi /var/lib/boot2docker/profile
5、
EXTRA_ARGS='
--registry-mirror=inkem9x5.mirror.aliyuncs.com
--label provider=virtualbox
'
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=no                 //auto改为no

并且删除了和tls相关的3行配置
6、sudo /etc/init.d/docker start       //success
`

期待更好的解决办法

**Comment by naruco** [comment]
这错误的原因，很可能是--registry-mirror设置有误；

建议修改成
``
--registry-mirror https://inkem9x5.mirror.aliyuncs.com
``
这样手动修改，貌似宿主机上的config.json里不会同步修改。

建议参考[boot2docker#insecure-registry](https://github.com/boot2docker/boot2docker#insecure-registry)进行命令式修改
修改你的error trace中第4步的内容：
``
docker-machine ssh text1 "echo $'EXTRA_ARGS=\"--registry-mirror https://inkem9x5.mirror.aliyuncs.com\"' | sudo tee -a /var/lib/boot2docker/profile && sudo /etc/init.d/docker restart"
``

**Comment by tianon** [comment]
Since this appears to be an issue of usage/configuration, I'm going to close -- if there's something we can fix here, a PR would be excellent. :+1:

In the future, help with debugging would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
