### ISSUE TITLE
[question] is it possible to build a tiny ubuntu iso instead?

### ISSUE THREAD

**Issue by skygragon** [boot2docker/boot2docker#1283]
just want a tiny ubuntu iso (with apt provided) that docker-machine could use to create new vms, did anyone ever try that?

**Comment by tianon** [comment]
I think these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

This repository is intended for the maintenance of the legacy boot2docker product.

The following POCs might be of additional interest:

- https://github.com/unclejack/debian2docker
- https://github.com/tianon/boot2docker-debian

Additionally, it's worth noting that `docker-machine` is built so that a stock Ubuntu installation should be completely usable (especially for cloud platforms, but works for local VMs too).
