### ISSUE TITLE
Remove debug flag from default daemon options

### ISSUE THREAD

**Issue by johnharris85** [boot2docker/boot2docker#1297]
Debug mode (`-D`) is set on by default for the daemon in boot2docker, although this prevents people from editing it through the config.json if they wish (as daemon flags cannot be overridden by config flags). Because `docker-machine` provides the ability to pass daemon flags then users can easily add this functionality if they want, but this also allows the freedom to use config.json as well.

TL;DR removing the `-D` default gives users greater flexibility.

Thoughts?

**Comment by tianon** [comment]
Sounds great (totally sane) to me, I think the following is the place that needs to change:

https://github.com/boot2docker/boot2docker/blob/0bb7bbd4cc0af0950cde50c0edd7efe1dee998ca/rootfs/rootfs/usr/local/etc/init.d/docker#L107-L108

**Comment by johnharris85** [comment]
Thanks @tianon. Do we need to make a note somewhere as while the impact is low, it does change default behaviour?

**Comment by tianon** [comment]
Naw, I don't think it's meaningful enough to warrant that -- it'll be in
the link of "changes" for folks looking around for why their logs are less
noisy.  Aligning closer to upstream's defaults in something as benign as
logging seems like enough of a good thing to not worry about it IMO
(especially since it's trivial for folks to re-enable if they really need
it).
