### ISSUE TITLE
How to try pre-releases?

### ISSUE THREAD

**Issue by leocavalcante** [boot2docker/boot2docker#1306]
How can I install a pre-release ISO? I've downloaded the v18.03.0-ce-rc1 to the `.docker/machine/cache` directory, but when I run `docker-machine upgrade` it tells that ISO is out-of-date and downloads v18.02.0-ce.

**Comment by tianon** [comment]
I'm not sure how to do it for `docker-machine upgrade`, but `docker-machine create` has a `--virtualbox-boot2docker-url` flag that can be used.  I believe it will also work if you replace the ISO in-place and use `docker-machine restart` instead of `upgrade`, but I haven't used `docker-machine` in a while, so my experience is likely outdated.

Hope that helps!
