### ISSUE TITLE
the tcz packages is old(out of date) how to update?

### ISSUE THREAD

**Issue by jianbosu** [boot2docker/boot2docker#1313]
may app when i run "tce-load -iw xxx.tcz" ,will get errors 
wget: server returned error 404 not found
xxx 4.9.tcz no such ifle
but i can sure  there is a xxx 4.14.tcz on the web

**Comment by tianon** [comment]
This is due to the nature of Tiny Core's packages and their dependencies.  When a package includes bits (such as kernel modules) which are for the specific kernel that Tiny Core itself builds and includes in their releases, they include that kernel's version number verbatim in the actual package name, and then any package which needs to depend on those packages includes `xxx-KERNEL` in their "deps" file.  In boot2docker, we need AUFS and thus get to compile our own kernel, so these particular Tiny Core packages cannot be used as-is.
