### ISSUE TITLE
Netfilter modules missing in version 18.09.05

### ISSUE THREAD

**Issue by borjator** [boot2docker/boot2docker#1389]
Hi,

I'm running boot2docker 18.09.5 and I have issues with the _iptables-save_ and _iptables-restore_ commands used by Rancher to set up port forwarding when deploying stacks:
```
iptables-restore v1.6.0: iptables-restore: unable to initialize table 'raw'
[...]
iptables-restore v1.6.0: Kernel module xt_set is not loaded in.
```

As in #1374 I miss a lot of iptables-related modules (for instance `xt_set.ko`):
```
# ls /lib/modules/$(uname -r)/kernel/net/ipv4/netfilter/
ipt_MASQUERADE.ko          nf_log_arp.ko
ipt_REJECT.ko              nf_log_ipv4.ko
iptable_filter.ko          nf_nat_ipv4.ko
iptable_nat.ko             nf_nat_masquerade_ipv4.ko
```

Am I missing something?

**Comment by borjator** [comment]
I think the _netfilter_ TCL extension is missing. I've tried to install it manually but the modules don't load and if I reboot the package is gone.

**Comment by tianon** [comment]
We don't use the kernel from Tiny Core Linux -- we build our own (especially since Docker is fairly dependent on kernel functionality).

The Netfilter bits we have currently come directly from Docker's requirements: https://github.com/boot2docker/boot2docker/blob/02c9101ce80345fb4ce3d7218f685dd1eafd5403/files/kernel-config.d/docker#L53-L56

If we ought to add more, there needs to be a reasonable case made for their usefulness and something like Debian's kernel configuration to give us a credible list of which ones are sane for us to do so with.

**Comment by borjator** [comment]
I have added a PR with the list of modules required by Rancher: https://github.com/boot2docker/boot2docker/pull/1391

**Comment by borjator** [comment]
Since the PR has been merged I can close this issue.

**Comment by borjator** [comment]
Since the PR has been merged I'll close the issue.
