### ISSUE TITLE
Linux -- Prompt when starting the host: “Waiting for an IP..."

### ISSUE THREAD

**Issue by Kry1702** [boot2docker/boot2docker#1399]
System Verson：CentOS Linux release 7.6.1810 (Core)
docker-machine Version：docker-machine version 0.16.1, build cce350d7
boot2docker Vserion：v19.03.1

use command "docker-machine --debug start manager" 
prompt：
(manager) DBG | Checking vm logs: /root/.docker/machine/machines/manager/manager/Logs/VBox.log
(manager) DBG | Getting to WaitForSSH function...
(manager) DBG | Using SSH client type: external
(manager) DBG | Using SSH private key: /root/.docker/machine/machines/manager/id_rsa (-rw-------)
(manager) DBG | &{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@127.0.0.1 -o IdentitiesOnly=yes -i /root/.docker/machine/machines/manager/id_rsa -p 35904] /usr/bin/ssh <nil>}
(manager) DBG | About to run SSH command:
(manager) DBG | exit 0
(manager) Waiting for an IP...
(manager) DBG | SSH cmd err, output: exit status 255: 
(manager) DBG | Error getting ssh command 'exit 0' : ssh command error:
(manager) DBG | command : exit 0
(manager) DBG | err     : exit status 255
(manager) DBG | output  :

use command "telnet  127.0.0.1 35904" 
prompt：
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused

use command “docker-machine ssh manager” 
Error: Cannot run SSH command: Host "manager" is not running

Native routing forwarding is enabled by default；

I tried to lower the version test: v18.09.8，
use command "docker-machine create -d virtualbox manager" ，no problem；
Continue to create the host;
use command "docker-machine create -d virtualbox manager" 
The result changes the state of the host I created for the first time from running to stopping.

After several attempts, only one host can exist in the state of running, and all other hosts are stopped. Multiple hosts can be started at the same time. The last one is in the state of running, and the rest are covered in the state of stopping.

**Comment by tianon** [comment]
Honestly, this seems like a an issue with `docker-machine`, VirtualBox, or something else in your environment or setup, so I'd recommend trying [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) for more help debugging and coming back here with a detailed issue (or even PR) only if it is determined that boot2docker itself is where the problem lies.

As-is, there's nothing here that points to this being an issue with boot2docker itself (and I'm not able to reproduce the issue).
