### ISSUE TITLE
Fix timezone on boot2docker VM

### ISSUE THREAD

**Issue by docwhat** [boot2docker/boot2docker#476]
When first bringing up the boot2docker (either `init` or `up`) boot2docker should copy (on the Mac, anyway) `/etc/localtime` to the VM.

This will fix the timezone within the boot2docker VM, which makes trouble shooting certain issues easier.

Example:

``` sh
# Without /etc/localtime
date +'%I:%M %p %Z' # returns 11:33 PM UTC

# With /etc/localtime (America/New_York)
date +'%I:%M %p %Z' # returns 07:33 PM EDT
```

**Comment by ARF1** [comment]
Is there any movement on this? Is it possible to set a timezone on a Windows boot2docker vm?

**Comment by tianon** [comment]
Doh, definitely unintentional -- I'll make a PR to add that back now. :+1:

**Comment by tianon** [comment]
(As a workaround, the current ISO should have `unsquashfs` installed, so you should be able to use that to extract the files you're looking for instead of using `mount`.)

**Comment by tianon** [comment]
In fact, you can probably just do something like `tce-load -wicl tzdata` and get them installed into `/usr/share/zoneinfo` too.

**Comment by tianon** [comment]
In fact, I'm going to close this issue now since I'd say `tce-load` or stealing files via a container is the way to do this if you need something other than UTC on the host for some reason -- if your container needs a particular timezone, I think you're better off setting up `/etc/localtime` appropriately there instead.

(But I'm still going to add `CONFIG_SQUASHFS` back.)

**Comment by tianon** [comment]
https://github.com/boot2docker/boot2docker/pull/1359 :+1:
