### ISSUE TITLE
FreeBSD port?

### ISSUE THREAD

**Issue by apennebaker-ni** [boot2docker/boot2docker#775]
Could we bring boot2docker to FreeBSD, to make it easier for Unix users to enjoy Docker?

**Comment by nlfiedler** [comment]
I'd like to see that as well.

**Comment by SvenDowideit** [comment]
what do you mean by FreeBSD port? what VM system would you be using to run the b2d linux?

(mostly, this requires a FreeBSD user / coder to add the VM engine driver (to docker-machine) and should not require changes to the b2d linux distro.

**Comment by lantw44** [comment]
FreeBSD supports VirtualBox and bhyve.

**Comment by znmeb** [comment]
@lantw44 Can VirtualBox on a FreeBSD host use the virtualization hardware on an Intel / AMD processor?

**Comment by lantw44** [comment]
@znmeb  Yes, VT-x/AMD-V is enabled in VirtualBox on FreeBSD.

**Comment by chantra** [comment]
I think the main issue will be mounting the homedir so one can run `docker` from the host and properly access the volumes that need to be mounted.
I have something working by using a combo of
https://github.com/chantra/boot2docker/commit/29dabecc316b609de84f699a9968ea7c4d858fd1 on the b2d side
and
https://github.com/chantra/machine/commit/74b5db67ec7d8f11c6e25427e130e5951623f4a8
on the docker-machine side.

The issue is that we can't mount the host `/home` in the VM so I trick that by creating `/hosthome` in the VM and, if the mount exist, I am linking the subdirs from the host's /home to the vm's /home

Unless there is a `docker` home dir on the host, it should work just fine.

**Comment by chantra** [comment]
I reckon that should work on BSD

**Comment by herrbischoff** [comment]
Any news regarding this? I'd really love to see Docker running on FreeBSD, even if it's in a VM. Maybe it's worth looking at how the FreeNAS folks have accomplished that. The newest release offers Docker support through what I can only speculate is boot2docker in bhyve.

**Comment by tianon** [comment]
At this point, this would be accomplished via `docker-machine`, not `boot2docker`.  This is simply a generic Linux distribution containing Docker which would then be used within a virtual machine, as has been described above.  If there are any specific changes required to the distribution to support running on a VM within FreeBSD (which seems unlikely), we should evaluate those in their own PRs. :+1:
