### ISSUE TITLE
Restart docker service with "service docker stop"  , start

### ISSUE THREAD

**Issue by ovidiubuligan** [boot2docker/boot2docker#782]
I use windows 7 and putty to access virtual box boot2docker-vm machine.
I am trying to restart docker service from ssh and i get:
`"sudo: service: command not found"`
Is service command not supported in boot2docker linux ? 
How can I restart the service without restarting the vm ?

**Comment by dave-tucker** [comment]
You can stop|start|restart docker using the init script.
For example:

```bash
sudo /etc/init.d/docker restart
````

**Comment by anvikakumar93** [comment]
It says /etc/init.d/ command not found :(

**Comment by aivaras-b** [comment]
or just 
`sudo service docker stop`
 and then
` sudo service docker start`

**Comment by aabuhasna** [comment]
Hi,
I am using debian 8 and when I try to execute `service docker stop` and` /etc/init.d/docker stop` nothing happened

**Comment by iarepandemonium** [comment]
On ubuntu and my docker has also gone rogue.  I can't stop it at all.

**Comment by clementm916** [comment]
Worked for me on Mac 
```
brew services start docker-machine
```

**Comment by ORESoftware** [comment]
/etc/init.d/docker: No such file or directory

**Comment by yosifkit** [comment]
If you are using `boot2docker`, then this question is solved: run the following from the VM `sudo /etc/init.d/docker restart`.  Since you most likely installed Docker using docker-toolbox you need to get to the VM; to do so, run `docker-machine ssh` and then run the restart command there.

If you are having trouble stopping or restarting your Docker daemon in places that are not boot2docker, then this is not the place to file that issue. Try the Docker forums: https://forums.docker.com/.

**Comment by aipirvu** [comment]
My problem was that I created the `daemon.json` file that was not properly formatted (the command that I created the file with removed the `"` around the property name and value making the json invalid. Fixed the file and the service started successfully. I assume a lot of people might have encountered this if they wanted to quickly test a image upload to a unsecured repository and had to edit this file.
