### ISSUE TITLE
Multiline cat fails when /tmp is mounted

### ISSUE THREAD

**Issue by cmlad** [boot2docker/boot2docker#864]
On OSX (at least), when /tmp is an external volume, the multiline cat command (with EOF delimiter/HERE document):

    cat << EOF
    asdf
    asdf
    EOF

fails with output:

    cat: -: No such file or directory

The expected result is:

    asdf
    asdf

This breaks some autoconf scripts. The issue is not present in a pure Linux Docker. You can test it by starting a container with the following command:

docker run -ti -v /Users/username/somedir:/tmp debian:wheezy /bin/bash

Also fails on ubuntu:latest, centos:centos6, and centos:centos7.

Here is the expected strace end:

    fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 1), ...}) = 0
    fstat(0, {st_mode=S_IFREG|0600, st_size=15, ...}) = 0
    fadvise64(0, 0, 0, POSIX_FADV_SEQUENTIAL) = 0
    read(0, "asdf\nasdf\n", 32768)    = 15
    write(1, "asdf\nasdf\n", 15asdf
    asdf
    )      = 15
    read(0, "", 32768)                      = 0
    close(0)                                = 0
    close(1)                                = 0
    close(2)                                = 0
    exit_group(0)                           = ?

Here is the erroneous strace:

    fstat(1, {st_mode=S_IFCHR|0622, st_rdev=makedev(136, 0), ...}) = 0
    fstat(0, 0x7fffa50aad50)                = -1 ENOENT (No such file or directory)
    write(2, "cat: ", 5cat: )                    = 5
    write(2, "-", 1-)                        = 1
    open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/share/locale/en_US.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/share/locale/en.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/share/locale/en.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    write(2, ": No such file or directory", 27: No such file or directory) = 27
    write(2, "\n", 1
    )                       = 1
    close(0)                                = 0
    close(1)                                = 0
    close(2)                                = 0
    exit_group(1)                           = ?

It seems to be some permissions issues, unfortunately the permissions of a mounted volume cannot be changed.

**Comment by yosifkit** [comment]
(sorry for the long tail on this issue)
The behavior described is to be expected for any executable that uses `/tmp` with the described setup. Any mounts coming from OSX are given a specific user and group ownership and inside the boot2docker VM (1000:50) and Linux utilities assume that any user has access to `/tmp`.  It might work if you `chmod 777` the folder on the Mac and then run your container.  I think the other solution is to just use [`--tmpfs /tmp`](https://docs.docker.com/engine/reference/commandline/run/#/mount-tmpfs---tmpfs).

Closing as this seems to be resolved. If you feel this issue was closed prematurely, please comment and let us know.
