### ISSUE TITLE
Disk performence is bad using -v 。Any suggestion？

### ISSUE THREAD

**Issue by going1000** [boot2docker/boot2docker#886]
I find the same issue in stackoverflow http://stackoverflow.com/questions/27402989/how-can-i-improve-the-performance-of-my-boot2docker-vm。

Any other solutions？Thank a lot。

**Comment by thaJeztah** [comment]
There are various existing issues covering this and this is a known limitation of the way directories on your host are shared with the boot2docker VM.

These issues may give you some hints; https://github.com/boot2docker/boot2docker/issues/593, https://github.com/boot2docker/boot2docker/issues/64

I think it's best to close this issue, because it's a duplicate of other issues

**Comment by going1000** [comment]
ok，thanks
